apiVersion: apps/v1
kind: Deployment
metadata:
  name: cowork
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cowork
  template:
    metadata:
      labels:
        app: cowork
    spec:
      containers:
        - name: cowork
          image: 963817942828.dkr.ecr.us-east-1.amazonaws.com/coworking:latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health_check
              port: 5153
            initialDelaySeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: "/readiness_check"
              port: 5153
            initialDelaySeconds: 5
            timeoutSeconds: 5

          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: POSTGRES_PASSWORD
            - name: DB_HOST
              value: postgres.default.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: POSTGRES_DB

          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: example
spec:
  selector:
    app: cowork
  ports:
  - name: "5153"
    protocol: TCP
    port: 5153
    targetPort: 5153
