apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{},"name":"manual-pv"},"spec":{"accessModes":["ReadWriteOnce"],"awsElasticBlockStore":{"fsType":"ext4","volumeID":"vol-0264f0ecdaedea25b"},"capacity":{"storage":"8Gi"},"persistentVolumeReclaimPolicy":"Retain","storageClassName":"gp2","volumeMode":"Filesystem"}}
  creationTimestamp: "2023-04-23T16:20:50Z"
  finalizers:
  - kubernetes.io/pv-protection
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:phase: {}
    manager: kube-controller-manager
    operation: Update
    subresource: status
    time: "2023-04-23T16:20:50Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        f:accessModes: {}
        f:awsElasticBlockStore:
          .: {}
          f:fsType: {}
          f:volumeID: {}
        f:capacity:
          .: {}
          f:storage: {}
        f:persistentVolumeReclaimPolicy: {}
        f:storageClassName: {}
        f:volumeMode: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2023-04-23T16:20:50Z"
  name: manual-pv
  resourceVersion: "166819"
  uid: a01ea3b2-f58b-41e9-a3e9-e85f0a81da22
spec:
  claimRef:
    name: data-postgres-postgresql-0
    namespace: default
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-0264f0ecdaedea25b
  capacity:
    storage: 8Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  volumeMode: Filesystem
status:
  phase: Available
