
#
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: default
type: Opaque
data:
  POSTGRES_DB: cG9zdGdyZXM=   #postgres
  POSTGRES_USER: cG9zdGdyZXM=   #postgres 
  POSTGRES_PASSWORD: YWRtaW4xMjM=     #admin123
