apiVersion: v1
kind: ConfigMap
metadata:
  name: coworking-env
data:
  DB_NAME: "postgres"
  DB_USERNAME: "username"
  DB_HOST: "10.100.11.185"
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_PASSWORD: cGFzc3dvcmQ=